export const SELECT_CS_NODE = "SELECT_CS_NODE";
export const FETCH_CHARTS_STARTED = "FETCH_CHARTS_STARTED";
export const FETCH_CHARTS_SUCCEEDED = "FETCH_CHARTS_SUCCEEDED";
export const FETCH_CHARTS_FAILED = "FETCH_CHARTS_FAILED";
export const CREATE_CHART_SUCCEDED = "CREATE_CHART_SUCCEDED";
export const EDIT_TASK = "EDIT_TASK";
export const FetchCharts = "FETCH_CHARTS";